package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppNavigationMenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuAllPropertiesEquals(AppNavigationMenu expected, AppNavigationMenu actual) {
        assertAppNavigationMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertAppNavigationMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuAllUpdatablePropertiesEquals(AppNavigationMenu expected, AppNavigationMenu actual) {
        assertAppNavigationMenuUpdatableFieldsEquals(expected, actual);
        assertAppNavigationMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuAutoGeneratedPropertiesEquals(AppNavigationMenu expected, AppNavigationMenu actual) {
        assertThat(actual)
            .as("Verify AppNavigationMenu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuUpdatableFieldsEquals(AppNavigationMenu expected, AppNavigationMenu actual) {
        assertThat(actual)
            .as("Verify AppNavigationMenu relevant properties")
            .satisfies(a -> assertThat(a.getMenuCode()).as("check menuCode").isEqualTo(expected.getMenuCode()))
            .satisfies(a -> assertThat(a.getMenuName()).as("check menuName").isEqualTo(expected.getMenuName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMenuType()).as("check menuType").isEqualTo(expected.getMenuType()))
            .satisfies(a -> assertThat(a.getIcon()).as("check icon").isEqualTo(expected.getIcon()))
            .satisfies(a -> assertThat(a.getRoutePath()).as("check routePath").isEqualTo(expected.getRoutePath()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuUpdatableRelationshipsEquals(AppNavigationMenu expected, AppNavigationMenu actual) {
        // empty method
    }
}
