package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppNavigationMenuItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuItemAllPropertiesEquals(AppNavigationMenuItem expected, AppNavigationMenuItem actual) {
        assertAppNavigationMenuItemAutoGeneratedPropertiesEquals(expected, actual);
        assertAppNavigationMenuItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuItemAllUpdatablePropertiesEquals(
        AppNavigationMenuItem expected,
        AppNavigationMenuItem actual
    ) {
        assertAppNavigationMenuItemUpdatableFieldsEquals(expected, actual);
        assertAppNavigationMenuItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuItemAutoGeneratedPropertiesEquals(
        AppNavigationMenuItem expected,
        AppNavigationMenuItem actual
    ) {
        assertThat(actual)
            .as("Verify AppNavigationMenuItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuItemUpdatableFieldsEquals(AppNavigationMenuItem expected, AppNavigationMenuItem actual) {
        assertThat(actual)
            .as("Verify AppNavigationMenuItem relevant properties")
            .satisfies(a -> assertThat(a.getItemCode()).as("check itemCode").isEqualTo(expected.getItemCode()))
            .satisfies(a -> assertThat(a.getItemName()).as("check itemName").isEqualTo(expected.getItemName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIcon()).as("check icon").isEqualTo(expected.getIcon()))
            .satisfies(a -> assertThat(a.getRoutePath()).as("check routePath").isEqualTo(expected.getRoutePath()))
            .satisfies(a -> assertThat(a.getComponentPath()).as("check componentPath").isEqualTo(expected.getComponentPath()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getBadgeText()).as("check badgeText").isEqualTo(expected.getBadgeText()))
            .satisfies(a -> assertThat(a.getBadgeColor()).as("check badgeColor").isEqualTo(expected.getBadgeColor()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuItemUpdatableRelationshipsEquals(
        AppNavigationMenuItem expected,
        AppNavigationMenuItem actual
    ) {
        assertThat(actual)
            .as("Verify AppNavigationMenuItem relationships")
            .satisfies(a -> assertThat(a.getParentMenu()).as("check parentMenu").isEqualTo(expected.getParentMenu()));
    }
}
