package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppNavigationMenuRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuRoleAllPropertiesEquals(AppNavigationMenuRole expected, AppNavigationMenuRole actual) {
        assertAppNavigationMenuRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertAppNavigationMenuRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuRoleAllUpdatablePropertiesEquals(
        AppNavigationMenuRole expected,
        AppNavigationMenuRole actual
    ) {
        assertAppNavigationMenuRoleUpdatableFieldsEquals(expected, actual);
        assertAppNavigationMenuRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuRoleAutoGeneratedPropertiesEquals(
        AppNavigationMenuRole expected,
        AppNavigationMenuRole actual
    ) {
        assertThat(actual)
            .as("Verify AppNavigationMenuRole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuRoleUpdatableFieldsEquals(AppNavigationMenuRole expected, AppNavigationMenuRole actual) {
        assertThat(actual)
            .as("Verify AppNavigationMenuRole relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNavigationMenuRoleUpdatableRelationshipsEquals(
        AppNavigationMenuRole expected,
        AppNavigationMenuRole actual
    ) {
        assertThat(actual)
            .as("Verify AppNavigationMenuRole relationships")
            .satisfies(a -> assertThat(a.getAppNavigationMenu()).as("check appNavigationMenu").isEqualTo(expected.getAppNavigationMenu()))
            .satisfies(a ->
                assertThat(a.getAppNavigationMenuItem()).as("check appNavigationMenuItem").isEqualTo(expected.getAppNavigationMenuItem())
            );
    }
}
