package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BillTaxAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillTaxAllPropertiesEquals(BillTax expected, BillTax actual) {
        assertBillTaxAutoGeneratedPropertiesEquals(expected, actual);
        assertBillTaxAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillTaxAllUpdatablePropertiesEquals(BillTax expected, BillTax actual) {
        assertBillTaxUpdatableFieldsEquals(expected, actual);
        assertBillTaxUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillTaxAutoGeneratedPropertiesEquals(BillTax expected, BillTax actual) {
        assertThat(actual)
            .as("Verify BillTax auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillTaxUpdatableFieldsEquals(BillTax expected, BillTax actual) {
        assertThat(actual)
            .as("Verify BillTax relevant properties")
            .satisfies(a -> assertThat(a.getTaxName()).as("check taxName").isEqualTo(expected.getTaxName()))
            .satisfies(a ->
                assertThat(a.getTaxRate()).as("check taxRate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxRate())
            )
            .satisfies(a ->
                assertThat(a.getTaxableAmount())
                    .as("check taxableAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxableAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillTaxUpdatableRelationshipsEquals(BillTax expected, BillTax actual) {
        assertThat(actual)
            .as("Verify BillTax relationships")
            .satisfies(a -> assertThat(a.getBill()).as("check bill").isEqualTo(expected.getBill()))
            .satisfies(a -> assertThat(a.getTaxConfig()).as("check taxConfig").isEqualTo(expected.getTaxConfig()));
    }
}
