package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BillItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillItemAllPropertiesEquals(BillItem expected, BillItem actual) {
        assertBillItemAutoGeneratedPropertiesEquals(expected, actual);
        assertBillItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillItemAllUpdatablePropertiesEquals(BillItem expected, BillItem actual) {
        assertBillItemUpdatableFieldsEquals(expected, actual);
        assertBillItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillItemAutoGeneratedPropertiesEquals(BillItem expected, BillItem actual) {
        assertThat(actual)
            .as("Verify BillItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillItemUpdatableFieldsEquals(BillItem expected, BillItem actual) {
        assertThat(actual)
            .as("Verify BillItem relevant properties")
            .satisfies(a -> assertThat(a.getItemName()).as("check itemName").isEqualTo(expected.getItemName()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getItemTotal()).as("check itemTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getItemTotal())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillItemUpdatableRelationshipsEquals(BillItem expected, BillItem actual) {
        assertThat(actual)
            .as("Verify BillItem relationships")
            .satisfies(a -> assertThat(a.getBill()).as("check bill").isEqualTo(expected.getBill()))
            .satisfies(a -> assertThat(a.getOrderItem()).as("check orderItem").isEqualTo(expected.getOrderItem()));
    }
}
