package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BillDiscountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillDiscountAllPropertiesEquals(BillDiscount expected, BillDiscount actual) {
        assertBillDiscountAutoGeneratedPropertiesEquals(expected, actual);
        assertBillDiscountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillDiscountAllUpdatablePropertiesEquals(BillDiscount expected, BillDiscount actual) {
        assertBillDiscountUpdatableFieldsEquals(expected, actual);
        assertBillDiscountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillDiscountAutoGeneratedPropertiesEquals(BillDiscount expected, BillDiscount actual) {
        assertThat(actual)
            .as("Verify BillDiscount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillDiscountUpdatableFieldsEquals(BillDiscount expected, BillDiscount actual) {
        assertThat(actual)
            .as("Verify BillDiscount relevant properties")
            .satisfies(a -> assertThat(a.getDiscountCode()).as("check discountCode").isEqualTo(expected.getDiscountCode()))
            .satisfies(a -> assertThat(a.getDiscountType()).as("check discountType").isEqualTo(expected.getDiscountType()))
            .satisfies(a ->
                assertThat(a.getDiscountValue())
                    .as("check discountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillDiscountUpdatableRelationshipsEquals(BillDiscount expected, BillDiscount actual) {
        assertThat(actual)
            .as("Verify BillDiscount relationships")
            .satisfies(a -> assertThat(a.getBill()).as("check bill").isEqualTo(expected.getBill()))
            .satisfies(a -> assertThat(a.getDiscount()).as("check discount").isEqualTo(expected.getDiscount()));
    }
}
