package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillAllPropertiesEquals(Bill expected, Bill actual) {
        assertBillAutoGeneratedPropertiesEquals(expected, actual);
        assertBillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillAllUpdatablePropertiesEquals(Bill expected, Bill actual) {
        assertBillUpdatableFieldsEquals(expected, actual);
        assertBillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillAutoGeneratedPropertiesEquals(Bill expected, Bill actual) {
        assertThat(actual)
            .as("Verify Bill auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillUpdatableFieldsEquals(Bill expected, Bill actual) {
        assertThat(actual)
            .as("Verify Bill relevant properties")
            .satisfies(a -> assertThat(a.getBillNumber()).as("check billNumber").isEqualTo(expected.getBillNumber()))
            .satisfies(a -> assertThat(a.getBillDate()).as("check billDate").isEqualTo(expected.getBillDate()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getServiceCharge())
                    .as("check serviceCharge")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getServiceCharge())
            )
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a ->
                assertThat(a.getAmountPaid())
                    .as("check amountPaid")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountPaid())
            )
            .satisfies(a ->
                assertThat(a.getAmountDue()).as("check amountDue").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmountDue())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getGeneratedBy()).as("check generatedBy").isEqualTo(expected.getGeneratedBy()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBillUpdatableRelationshipsEquals(Bill expected, Bill actual) {
        assertThat(actual)
            .as("Verify Bill relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()))
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
