package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BranchTableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchTableAllPropertiesEquals(BranchTable expected, BranchTable actual) {
        assertBranchTableAutoGeneratedPropertiesEquals(expected, actual);
        assertBranchTableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchTableAllUpdatablePropertiesEquals(BranchTable expected, BranchTable actual) {
        assertBranchTableUpdatableFieldsEquals(expected, actual);
        assertBranchTableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchTableAutoGeneratedPropertiesEquals(BranchTable expected, BranchTable actual) {
        assertThat(actual)
            .as("Verify BranchTable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchTableUpdatableFieldsEquals(BranchTable expected, BranchTable actual) {
        assertThat(actual)
            .as("Verify BranchTable relevant properties")
            .satisfies(a -> assertThat(a.getTableNumber()).as("check tableNumber").isEqualTo(expected.getTableNumber()))
            .satisfies(a -> assertThat(a.getTableName()).as("check tableName").isEqualTo(expected.getTableName()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getFloor()).as("check floor").isEqualTo(expected.getFloor()))
            .satisfies(a -> assertThat(a.getSection()).as("check section").isEqualTo(expected.getSection()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getQrCode()).as("check qrCode").isEqualTo(expected.getQrCode()))
            .satisfies(a -> assertThat(a.getQrCodeUrl()).as("check qrCodeUrl").isEqualTo(expected.getQrCodeUrl()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchTableUpdatableRelationshipsEquals(BranchTable expected, BranchTable actual) {
        assertThat(actual)
            .as("Verify BranchTable relationships")
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()));
    }
}
