package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BranchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchAllPropertiesEquals(Branch expected, Branch actual) {
        assertBranchAutoGeneratedPropertiesEquals(expected, actual);
        assertBranchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchAllUpdatablePropertiesEquals(Branch expected, Branch actual) {
        assertBranchUpdatableFieldsEquals(expected, actual);
        assertBranchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchAutoGeneratedPropertiesEquals(Branch expected, Branch actual) {
        assertThat(actual)
            .as("Verify Branch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUpdatableFieldsEquals(Branch expected, Branch actual) {
        assertThat(actual)
            .as("Verify Branch relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getContactEmail()).as("check contactEmail").isEqualTo(expected.getContactEmail()))
            .satisfies(a -> assertThat(a.getContactPhone()).as("check contactPhone").isEqualTo(expected.getContactPhone()))
            .satisfies(a -> assertThat(a.getAddressLine1()).as("check addressLine1").isEqualTo(expected.getAddressLine1()))
            .satisfies(a -> assertThat(a.getAddressLine2()).as("check addressLine2").isEqualTo(expected.getAddressLine2()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getPostalCode()).as("check postalCode").isEqualTo(expected.getPostalCode()))
            .satisfies(a ->
                assertThat(a.getLatitude()).as("check latitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLatitude())
            )
            .satisfies(a ->
                assertThat(a.getLongitude()).as("check longitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLongitude())
            )
            .satisfies(a -> assertThat(a.getOpeningTime()).as("check openingTime").isEqualTo(expected.getOpeningTime()))
            .satisfies(a -> assertThat(a.getClosingTime()).as("check closingTime").isEqualTo(expected.getClosingTime()))
            .satisfies(a -> assertThat(a.getTimezone()).as("check timezone").isEqualTo(expected.getTimezone()))
            .satisfies(a -> assertThat(a.getMaxCapacity()).as("check maxCapacity").isEqualTo(expected.getMaxCapacity()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUpdatableRelationshipsEquals(Branch expected, Branch actual) {
        assertThat(actual)
            .as("Verify Branch relationships")
            .satisfies(a -> assertThat(a.getRestaurant()).as("check restaurant").isEqualTo(expected.getRestaurant()));
    }
}
