package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CustomerLoyaltyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerLoyaltyAllPropertiesEquals(CustomerLoyalty expected, CustomerLoyalty actual) {
        assertCustomerLoyaltyAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerLoyaltyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerLoyaltyAllUpdatablePropertiesEquals(CustomerLoyalty expected, CustomerLoyalty actual) {
        assertCustomerLoyaltyUpdatableFieldsEquals(expected, actual);
        assertCustomerLoyaltyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerLoyaltyAutoGeneratedPropertiesEquals(CustomerLoyalty expected, CustomerLoyalty actual) {
        assertThat(actual)
            .as("Verify CustomerLoyalty auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerLoyaltyUpdatableFieldsEquals(CustomerLoyalty expected, CustomerLoyalty actual) {
        assertThat(actual)
            .as("Verify CustomerLoyalty relevant properties")
            .satisfies(a ->
                assertThat(a.getLoyaltyPoints())
                    .as("check loyaltyPoints")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getLoyaltyPoints())
            )
            .satisfies(a -> assertThat(a.getTier()).as("check tier").isEqualTo(expected.getTier()))
            .satisfies(a -> assertThat(a.getEnrolledAt()).as("check enrolledAt").isEqualTo(expected.getEnrolledAt()))
            .satisfies(a -> assertThat(a.getLastPointsEarnedAt()).as("check lastPointsEarnedAt").isEqualTo(expected.getLastPointsEarnedAt())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerLoyaltyUpdatableRelationshipsEquals(CustomerLoyalty expected, CustomerLoyalty actual) {
        assertThat(actual)
            .as("Verify CustomerLoyalty relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getRestaurant()).as("check restaurant").isEqualTo(expected.getRestaurant()));
    }
}
