package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DiscountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscountAllPropertiesEquals(Discount expected, Discount actual) {
        assertDiscountAutoGeneratedPropertiesEquals(expected, actual);
        assertDiscountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscountAllUpdatablePropertiesEquals(Discount expected, Discount actual) {
        assertDiscountUpdatableFieldsEquals(expected, actual);
        assertDiscountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscountAutoGeneratedPropertiesEquals(Discount expected, Discount actual) {
        assertThat(actual)
            .as("Verify Discount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscountUpdatableFieldsEquals(Discount expected, Discount actual) {
        assertThat(actual)
            .as("Verify Discount relevant properties")
            .satisfies(a -> assertThat(a.getDiscountCode()).as("check discountCode").isEqualTo(expected.getDiscountCode()))
            .satisfies(a -> assertThat(a.getDiscountName()).as("check discountName").isEqualTo(expected.getDiscountName()))
            .satisfies(a -> assertThat(a.getDiscountType()).as("check discountType").isEqualTo(expected.getDiscountType()))
            .satisfies(a ->
                assertThat(a.getDiscountValue())
                    .as("check discountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getMinOrderAmount())
                    .as("check minOrderAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMinOrderAmount())
            )
            .satisfies(a ->
                assertThat(a.getMaxDiscountAmount())
                    .as("check maxDiscountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMaxDiscountAmount())
            )
            .satisfies(a -> assertThat(a.getApplicableTo()).as("check applicableTo").isEqualTo(expected.getApplicableTo()))
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidTo()).as("check validTo").isEqualTo(expected.getValidTo()))
            .satisfies(a -> assertThat(a.getMaxUses()).as("check maxUses").isEqualTo(expected.getMaxUses()))
            .satisfies(a -> assertThat(a.getCurrentUses()).as("check currentUses").isEqualTo(expected.getCurrentUses()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscountUpdatableRelationshipsEquals(Discount expected, Discount actual) {
        assertThat(actual)
            .as("Verify Discount relationships")
            .satisfies(a -> assertThat(a.getRestaurant()).as("check restaurant").isEqualTo(expected.getRestaurant()));
    }
}
