package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InventoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryAllPropertiesEquals(Inventory expected, Inventory actual) {
        assertInventoryAutoGeneratedPropertiesEquals(expected, actual);
        assertInventoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryAllUpdatablePropertiesEquals(Inventory expected, Inventory actual) {
        assertInventoryUpdatableFieldsEquals(expected, actual);
        assertInventoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryAutoGeneratedPropertiesEquals(Inventory expected, Inventory actual) {
        assertThat(actual)
            .as("Verify Inventory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryUpdatableFieldsEquals(Inventory expected, Inventory actual) {
        assertThat(actual)
            .as("Verify Inventory relevant properties")
            .satisfies(a ->
                assertThat(a.getCurrentStock())
                    .as("check currentStock")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentStock())
            )
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a ->
                assertThat(a.getMinStockLevel())
                    .as("check minStockLevel")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMinStockLevel())
            )
            .satisfies(a ->
                assertThat(a.getMaxStockLevel())
                    .as("check maxStockLevel")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMaxStockLevel())
            )
            .satisfies(a -> assertThat(a.getLastUpdatedAt()).as("check lastUpdatedAt").isEqualTo(expected.getLastUpdatedAt()))
            .satisfies(a -> assertThat(a.getLastUpdatedBy()).as("check lastUpdatedBy").isEqualTo(expected.getLastUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryUpdatableRelationshipsEquals(Inventory expected, Inventory actual) {
        assertThat(actual)
            .as("Verify Inventory relationships")
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()))
            .satisfies(a -> assertThat(a.getMenuItem()).as("check menuItem").isEqualTo(expected.getMenuItem()));
    }
}
