package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryAllPropertiesEquals(MenuCategory expected, MenuCategory actual) {
        assertMenuCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryAllUpdatablePropertiesEquals(MenuCategory expected, MenuCategory actual) {
        assertMenuCategoryUpdatableFieldsEquals(expected, actual);
        assertMenuCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryAutoGeneratedPropertiesEquals(MenuCategory expected, MenuCategory actual) {
        assertThat(actual)
            .as("Verify MenuCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryUpdatableFieldsEquals(MenuCategory expected, MenuCategory actual) {
        assertThat(actual)
            .as("Verify MenuCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryUpdatableRelationshipsEquals(MenuCategory expected, MenuCategory actual) {
        assertThat(actual)
            .as("Verify MenuCategory relationships")
            .satisfies(a -> assertThat(a.getRestaurant()).as("check restaurant").isEqualTo(expected.getRestaurant()));
    }
}
