package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemAddonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAddonAllPropertiesEquals(MenuItemAddon expected, MenuItemAddon actual) {
        assertMenuItemAddonAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemAddonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAddonAllUpdatablePropertiesEquals(MenuItemAddon expected, MenuItemAddon actual) {
        assertMenuItemAddonUpdatableFieldsEquals(expected, actual);
        assertMenuItemAddonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAddonAutoGeneratedPropertiesEquals(MenuItemAddon expected, MenuItemAddon actual) {
        assertThat(actual)
            .as("Verify MenuItemAddon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAddonUpdatableFieldsEquals(MenuItemAddon expected, MenuItemAddon actual) {
        assertThat(actual)
            .as("Verify MenuItemAddon relevant properties")
            .satisfies(a -> assertThat(a.getAddonName()).as("check addonName").isEqualTo(expected.getAddonName()))
            .satisfies(a -> assertThat(a.getAddonCode()).as("check addonCode").isEqualTo(expected.getAddonCode()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAddonUpdatableRelationshipsEquals(MenuItemAddon expected, MenuItemAddon actual) {
        assertThat(actual)
            .as("Verify MenuItemAddon relationships")
            .satisfies(a -> assertThat(a.getMenuItem()).as("check menuItem").isEqualTo(expected.getMenuItem()));
    }
}
