package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemVariantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemVariantAllPropertiesEquals(MenuItemVariant expected, MenuItemVariant actual) {
        assertMenuItemVariantAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemVariantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemVariantAllUpdatablePropertiesEquals(MenuItemVariant expected, MenuItemVariant actual) {
        assertMenuItemVariantUpdatableFieldsEquals(expected, actual);
        assertMenuItemVariantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemVariantAutoGeneratedPropertiesEquals(MenuItemVariant expected, MenuItemVariant actual) {
        assertThat(actual)
            .as("Verify MenuItemVariant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemVariantUpdatableFieldsEquals(MenuItemVariant expected, MenuItemVariant actual) {
        assertThat(actual)
            .as("Verify MenuItemVariant relevant properties")
            .satisfies(a -> assertThat(a.getVariantName()).as("check variantName").isEqualTo(expected.getVariantName()))
            .satisfies(a -> assertThat(a.getVariantCode()).as("check variantCode").isEqualTo(expected.getVariantCode()))
            .satisfies(a ->
                assertThat(a.getPriceModifier())
                    .as("check priceModifier")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPriceModifier())
            )
            .satisfies(a -> assertThat(a.getIsDefault()).as("check isDefault").isEqualTo(expected.getIsDefault()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemVariantUpdatableRelationshipsEquals(MenuItemVariant expected, MenuItemVariant actual) {
        assertThat(actual)
            .as("Verify MenuItemVariant relationships")
            .satisfies(a -> assertThat(a.getMenuItem()).as("check menuItem").isEqualTo(expected.getMenuItem()));
    }
}
