package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryAllPropertiesEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertOrderStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryAllUpdatablePropertiesEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertOrderStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertOrderStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryAutoGeneratedPropertiesEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertThat(actual)
            .as("Verify OrderStatusHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryUpdatableFieldsEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertThat(actual)
            .as("Verify OrderStatusHistory relevant properties")
            .satisfies(a -> assertThat(a.getPreviousStatus()).as("check previousStatus").isEqualTo(expected.getPreviousStatus()))
            .satisfies(a -> assertThat(a.getNewStatus()).as("check newStatus").isEqualTo(expected.getNewStatus()))
            .satisfies(a -> assertThat(a.getChangedAt()).as("check changedAt").isEqualTo(expected.getChangedAt()))
            .satisfies(a -> assertThat(a.getChangedBy()).as("check changedBy").isEqualTo(expected.getChangedBy()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryUpdatableRelationshipsEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertThat(actual)
            .as("Verify OrderStatusHistory relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }
}
