package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrderItemCustomizationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemCustomizationAllPropertiesEquals(OrderItemCustomization expected, OrderItemCustomization actual) {
        assertOrderItemCustomizationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderItemCustomizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemCustomizationAllUpdatablePropertiesEquals(
        OrderItemCustomization expected,
        OrderItemCustomization actual
    ) {
        assertOrderItemCustomizationUpdatableFieldsEquals(expected, actual);
        assertOrderItemCustomizationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemCustomizationAutoGeneratedPropertiesEquals(
        OrderItemCustomization expected,
        OrderItemCustomization actual
    ) {
        assertThat(actual)
            .as("Verify OrderItemCustomization auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemCustomizationUpdatableFieldsEquals(OrderItemCustomization expected, OrderItemCustomization actual) {
        assertThat(actual)
            .as("Verify OrderItemCustomization relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getTotalPrice())
                    .as("check totalPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemCustomizationUpdatableRelationshipsEquals(
        OrderItemCustomization expected,
        OrderItemCustomization actual
    ) {
        assertThat(actual)
            .as("Verify OrderItemCustomization relationships")
            .satisfies(a -> assertThat(a.getOrderItem()).as("check orderItem").isEqualTo(expected.getOrderItem()))
            .satisfies(a -> assertThat(a.getMenuItemAddon()).as("check menuItemAddon").isEqualTo(expected.getMenuItemAddon()));
    }
}
