package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RmsUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRmsUserAllPropertiesEquals(RmsUser expected, RmsUser actual) {
        assertRmsUserAutoGeneratedPropertiesEquals(expected, actual);
        assertRmsUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRmsUserAllUpdatablePropertiesEquals(RmsUser expected, RmsUser actual) {
        assertRmsUserUpdatableFieldsEquals(expected, actual);
        assertRmsUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRmsUserAutoGeneratedPropertiesEquals(RmsUser expected, RmsUser actual) {
        assertThat(actual)
            .as("Verify RmsUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRmsUserUpdatableFieldsEquals(RmsUser expected, RmsUser actual) {
        assertThat(actual)
            .as("Verify RmsUser relevant properties")
            .satisfies(a -> assertThat(a.getExternalUserId()).as("check externalUserId").isEqualTo(expected.getExternalUserId()))
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getProfileImageUrl()).as("check profileImageUrl").isEqualTo(expected.getProfileImageUrl()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getLastSyncAt()).as("check lastSyncAt").isEqualTo(expected.getLastSyncAt()))
            .satisfies(a -> assertThat(a.getSyncStatus()).as("check syncStatus").isEqualTo(expected.getSyncStatus()))
            .satisfies(a -> assertThat(a.getSyncError()).as("check syncError").isEqualTo(expected.getSyncError()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRmsUserUpdatableRelationshipsEquals(RmsUser expected, RmsUser actual) {
        // empty method
    }
}
