package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShiftAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAllPropertiesEquals(Shift expected, Shift actual) {
        assertShiftAutoGeneratedPropertiesEquals(expected, actual);
        assertShiftAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAllUpdatablePropertiesEquals(Shift expected, Shift actual) {
        assertShiftUpdatableFieldsEquals(expected, actual);
        assertShiftUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAutoGeneratedPropertiesEquals(Shift expected, Shift actual) {
        assertThat(actual)
            .as("Verify Shift auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftUpdatableFieldsEquals(Shift expected, Shift actual) {
        assertThat(actual)
            .as("Verify Shift relevant properties")
            .satisfies(a -> assertThat(a.getShiftName()).as("check shiftName").isEqualTo(expected.getShiftName()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getShiftDate()).as("check shiftDate").isEqualTo(expected.getShiftDate()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftUpdatableRelationshipsEquals(Shift expected, Shift actual) {
        assertThat(actual)
            .as("Verify Shift relationships")
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()));
    }
}
