package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TableWaiterAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableWaiterAssignmentAllPropertiesEquals(TableWaiterAssignment expected, TableWaiterAssignment actual) {
        assertTableWaiterAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTableWaiterAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableWaiterAssignmentAllUpdatablePropertiesEquals(
        TableWaiterAssignment expected,
        TableWaiterAssignment actual
    ) {
        assertTableWaiterAssignmentUpdatableFieldsEquals(expected, actual);
        assertTableWaiterAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableWaiterAssignmentAutoGeneratedPropertiesEquals(
        TableWaiterAssignment expected,
        TableWaiterAssignment actual
    ) {
        assertThat(actual)
            .as("Verify TableWaiterAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableWaiterAssignmentUpdatableFieldsEquals(TableWaiterAssignment expected, TableWaiterAssignment actual) {
        assertThat(actual)
            .as("Verify TableWaiterAssignment relevant properties")
            .satisfies(a -> assertThat(a.getAssignmentDate()).as("check assignmentDate").isEqualTo(expected.getAssignmentDate()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableWaiterAssignmentUpdatableRelationshipsEquals(
        TableWaiterAssignment expected,
        TableWaiterAssignment actual
    ) {
        assertThat(actual)
            .as("Verify TableWaiterAssignment relationships")
            .satisfies(a -> assertThat(a.getTableAssignment()).as("check tableAssignment").isEqualTo(expected.getTableAssignment()))
            .satisfies(a -> assertThat(a.getWaiter()).as("check waiter").isEqualTo(expected.getWaiter()));
    }
}
