package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TableAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableAssignmentAllPropertiesEquals(TableAssignment expected, TableAssignment actual) {
        assertTableAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTableAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableAssignmentAllUpdatablePropertiesEquals(TableAssignment expected, TableAssignment actual) {
        assertTableAssignmentUpdatableFieldsEquals(expected, actual);
        assertTableAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableAssignmentAutoGeneratedPropertiesEquals(TableAssignment expected, TableAssignment actual) {
        assertThat(actual)
            .as("Verify TableAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableAssignmentUpdatableFieldsEquals(TableAssignment expected, TableAssignment actual) {
        assertThat(actual)
            .as("Verify TableAssignment relevant properties")
            .satisfies(a -> assertThat(a.getAssignmentDate()).as("check assignmentDate").isEqualTo(expected.getAssignmentDate()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTableAssignmentUpdatableRelationshipsEquals(TableAssignment expected, TableAssignment actual) {
        assertThat(actual)
            .as("Verify TableAssignment relationships")
            .satisfies(a -> assertThat(a.getBranchTable()).as("check branchTable").isEqualTo(expected.getBranchTable()))
            .satisfies(a -> assertThat(a.getShift()).as("check shift").isEqualTo(expected.getShift()))
            .satisfies(a -> assertThat(a.getSupervisor()).as("check supervisor").isEqualTo(expected.getSupervisor()));
    }
}
