package com.atparui.rmsservice.domain;

import static com.atparui.rmsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TaxConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxConfigAllPropertiesEquals(TaxConfig expected, TaxConfig actual) {
        assertTaxConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertTaxConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxConfigAllUpdatablePropertiesEquals(TaxConfig expected, TaxConfig actual) {
        assertTaxConfigUpdatableFieldsEquals(expected, actual);
        assertTaxConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxConfigAutoGeneratedPropertiesEquals(TaxConfig expected, TaxConfig actual) {
        assertThat(actual)
            .as("Verify TaxConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxConfigUpdatableFieldsEquals(TaxConfig expected, TaxConfig actual) {
        assertThat(actual)
            .as("Verify TaxConfig relevant properties")
            .satisfies(a -> assertThat(a.getTaxName()).as("check taxName").isEqualTo(expected.getTaxName()))
            .satisfies(a -> assertThat(a.getTaxCode()).as("check taxCode").isEqualTo(expected.getTaxCode()))
            .satisfies(a ->
                assertThat(a.getTaxRate()).as("check taxRate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxRate())
            )
            .satisfies(a -> assertThat(a.getTaxType()).as("check taxType").isEqualTo(expected.getTaxType()))
            .satisfies(a -> assertThat(a.getIsApplicableToFood()).as("check isApplicableToFood").isEqualTo(expected.getIsApplicableToFood())
            )
            .satisfies(a ->
                assertThat(a.getIsApplicableToBeverage()).as("check isApplicableToBeverage").isEqualTo(expected.getIsApplicableToBeverage())
            )
            .satisfies(a ->
                assertThat(a.getIsApplicableToAlcohol()).as("check isApplicableToAlcohol").isEqualTo(expected.getIsApplicableToAlcohol())
            )
            .satisfies(a -> assertThat(a.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(expected.getEffectiveFrom()))
            .satisfies(a -> assertThat(a.getEffectiveTo()).as("check effectiveTo").isEqualTo(expected.getEffectiveTo()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxConfigUpdatableRelationshipsEquals(TaxConfig expected, TaxConfig actual) {
        assertThat(actual)
            .as("Verify TaxConfig relationships")
            .satisfies(a -> assertThat(a.getRestaurant()).as("check restaurant").isEqualTo(expected.getRestaurant()));
    }
}
