package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserBranchRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserBranchRoleAllPropertiesEquals(UserBranchRole expected, UserBranchRole actual) {
        assertUserBranchRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertUserBranchRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserBranchRoleAllUpdatablePropertiesEquals(UserBranchRole expected, UserBranchRole actual) {
        assertUserBranchRoleUpdatableFieldsEquals(expected, actual);
        assertUserBranchRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserBranchRoleAutoGeneratedPropertiesEquals(UserBranchRole expected, UserBranchRole actual) {
        assertThat(actual)
            .as("Verify UserBranchRole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserBranchRoleUpdatableFieldsEquals(UserBranchRole expected, UserBranchRole actual) {
        assertThat(actual)
            .as("Verify UserBranchRole relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getAssignedAt()).as("check assignedAt").isEqualTo(expected.getAssignedAt()))
            .satisfies(a -> assertThat(a.getAssignedBy()).as("check assignedBy").isEqualTo(expected.getAssignedBy()))
            .satisfies(a -> assertThat(a.getRevokedAt()).as("check revokedAt").isEqualTo(expected.getRevokedAt()))
            .satisfies(a -> assertThat(a.getRevokedBy()).as("check revokedBy").isEqualTo(expected.getRevokedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserBranchRoleUpdatableRelationshipsEquals(UserBranchRole expected, UserBranchRole actual) {
        assertThat(actual)
            .as("Verify UserBranchRole relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()));
    }
}
