package com.atparui.rmsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSyncLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSyncLogAllPropertiesEquals(UserSyncLog expected, UserSyncLog actual) {
        assertUserSyncLogAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSyncLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSyncLogAllUpdatablePropertiesEquals(UserSyncLog expected, UserSyncLog actual) {
        assertUserSyncLogUpdatableFieldsEquals(expected, actual);
        assertUserSyncLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSyncLogAutoGeneratedPropertiesEquals(UserSyncLog expected, UserSyncLog actual) {
        assertThat(actual)
            .as("Verify UserSyncLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSyncLogUpdatableFieldsEquals(UserSyncLog expected, UserSyncLog actual) {
        assertThat(actual)
            .as("Verify UserSyncLog relevant properties")
            .satisfies(a -> assertThat(a.getSyncType()).as("check syncType").isEqualTo(expected.getSyncType()))
            .satisfies(a -> assertThat(a.getSyncStatus()).as("check syncStatus").isEqualTo(expected.getSyncStatus()))
            .satisfies(a -> assertThat(a.getExternalUserId()).as("check externalUserId").isEqualTo(expected.getExternalUserId()))
            .satisfies(a -> assertThat(a.getRequestPayload()).as("check requestPayload").isEqualTo(expected.getRequestPayload()))
            .satisfies(a -> assertThat(a.getResponsePayload()).as("check responsePayload").isEqualTo(expected.getResponsePayload()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getSyncedAt()).as("check syncedAt").isEqualTo(expected.getSyncedAt()))
            .satisfies(a -> assertThat(a.getSyncedBy()).as("check syncedBy").isEqualTo(expected.getSyncedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSyncLogUpdatableRelationshipsEquals(UserSyncLog expected, UserSyncLog actual) {
        assertThat(actual)
            .as("Verify UserSyncLog relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
